import { useMutation, useQueryClient } from "@tanstack/react-query";
import { router } from "expo-router";
import { useState } from "react";
import { View } from "react-native";
import { ApiError, NetworkError } from "@pool/api-client";
import { PROJECT_TYPES, PROJECT_TYPE_LABELS, type ProjectType, type SessionUser } from "@pool/types";
import { createProjectSchema } from "@pool/validation";
import { parseMoneyToCents } from "@pool/core";
import { Button, Card, Chips, DateField, Screen, SectionHeader, Select, Text, TextField } from "@/components/ui";
import { useApi } from "@/features/data";
import { api } from "@/lib/api";
import { currentLocation } from "@/lib/location";
import { useSync } from "@/providers/sync";

/**
 * New project. The client and property are captured once here and reused
 * everywhere (maps, weather, documents, reports, client portal). Stages,
 * stage tasks with checklists and the dependency chain are generated by the
 * server from the company's stage templates.
 */
export default function NewProject() {
  const qc = useQueryClient();
  const { syncNow } = useSync();
  const users = useApi<SessionUser[]>(["users", "pm"], "/users", { role: "project_manager" });
  const teams = useApi<{ id: string; name: string; kind: string }[]>(["teams"], "/teams");
  const [clientMode, setClientMode] = useState<"new" | "existing">("new");
  const clients = useApi<{ id: string; fullName: string }[]>(["clients"], clientMode === "existing" ? "/clients" : null, { limit: 200 });
  const [form, setForm] = useState({
    name: "",
    type: "new_construction" as ProjectType,
    contract: "",
    estimate: "",
    plannedStartDate: null as string | null,
    projectManagerId: null as string | null,
    crewTeamId: null as string | null,
    clientId: null as string | null,
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    line1: "",
    city: "",
    region: "",
    postalCode: "",
    location: null as { latitude: number; longitude: number; accuracyMeters?: number | null } | null,
  });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const set = <K extends keyof typeof form>(k: K) => (v: (typeof form)[K]) => setForm((f) => ({ ...f, [k]: v }));
  const [locating, setLocating] = useState(false);

  const create = useMutation({
    mutationFn: async () => {
      const body = {
        name: form.name,
        type: form.type,
        status: "contract",
        contractAmountCents: parseMoneyToCents(form.contract) ?? 0,
        estimatedCostCents: parseMoneyToCents(form.estimate) ?? 0,
        plannedStartDate: form.plannedStartDate,
        projectManagerId: form.projectManagerId,
        crewTeamId: form.crewTeamId,
        ...(clientMode === "existing"
          ? { clientId: form.clientId }
          : { client: { firstName: form.firstName, lastName: form.lastName, email: form.email || null, phone: form.phone || null, preferredContact: "phone" } }),
        property: {
          address: { line1: form.line1, city: form.city, region: form.region, postalCode: form.postalCode, country: "US" },
          location: form.location,
        },
      };
      const parsed = createProjectSchema.safeParse(body);
      if (!parsed.success) {
        const e: Record<string, string> = {};
        for (const i of parsed.error.issues) e[i.path.join(".")] = i.message;
        setErrors(e);
        throw new Error("validation");
      }
      setErrors({});
      return api.post<{ id: string }>("/projects", parsed.data);
    },
    onSuccess: async (p) => {
      await syncNow();
      void qc.invalidateQueries();
      router.replace(`/projects/${p.id}`);
    },
    onError: (e) => {
      if (e instanceof ApiError) setErrors({ _: e.message });
      else if (e instanceof NetworkError) setErrors({ _: "Creating a project needs a connection." });
      else if (e instanceof Error && e.message !== "validation") setErrors({ _: e.message });
    },
  });

  const useGps = async () => {
    setLocating(true);
    const loc = await currentLocation({ ask: true });
    setLocating(false);
    if (loc) set("location")(loc);
    else setErrors((e) => ({ ...e, location: "Location permission is off or unavailable." }));
  };

  return (
    <Screen title="New project" back>
      <View className="gap-4">
        <TextField label="Project name" value={form.name} onChangeText={set("name")} error={errors.name} required placeholder="e.g. Nguyen Backyard Pool" />
        <Select label="Project type" value={form.type} onChange={(v) => v && set("type")(v)} options={PROJECT_TYPES.map((t) => ({ value: t, label: PROJECT_TYPE_LABELS[t] }))} />
        <View className="flex-row gap-3">
          <TextField className="flex-1" label="Contract amount" value={form.contract} onChangeText={set("contract")} keyboardType="decimal-pad" placeholder="$0.00" />
          <TextField className="flex-1" label="Estimated cost" value={form.estimate} onChangeText={set("estimate")} keyboardType="decimal-pad" placeholder="$0.00" />
        </View>
        <DateField label="Planned start" value={form.plannedStartDate} onChange={set("plannedStartDate")} error={errors.plannedCompletionDate} />
        <Text variant="caption">With a start date, every stage and its tasks are scheduled automatically.</Text>
        <Select label="Project manager" value={form.projectManagerId} allowClear onChange={set("projectManagerId")} options={(users.data ?? []).map((u) => ({ value: u.id, label: u.fullName }))} />
        <Select label="Crew" value={form.crewTeamId} allowClear onChange={set("crewTeamId")} options={(teams.data ?? []).filter((t) => t.kind === "crew").map((t) => ({ value: t.id, label: t.name }))} />

        <SectionHeader title="Client" />
        <Chips value={clientMode} onChange={setClientMode} options={[{ value: "new", label: "New client" }, { value: "existing", label: "Existing client" }]} />
        {clientMode === "new" ? (
          <>
            <View className="flex-row gap-3">
              <TextField className="flex-1" label="First name" value={form.firstName} onChangeText={set("firstName")} error={errors["client.firstName"]} required />
              <TextField className="flex-1" label="Last name" value={form.lastName} onChangeText={set("lastName")} error={errors["client.lastName"]} required />
            </View>
            <TextField label="Phone" value={form.phone} onChangeText={set("phone")} keyboardType="phone-pad" />
            <TextField label="Email" value={form.email} onChangeText={set("email")} keyboardType="email-address" autoCapitalize="none" error={errors["client.email"]} />
          </>
        ) : (
          <Select label="Client" value={form.clientId} onChange={set("clientId")} error={errors.clientId} options={(clients.data ?? []).map((c) => ({ value: c.id, label: c.fullName }))} />
        )}

        <SectionHeader title="Property" />
        <TextField label="Street address" value={form.line1} onChangeText={set("line1")} error={errors["property.address.line1"]} required autoComplete="street-address" />
        <View className="flex-row gap-3">
          <TextField className="flex-[2]" label="City" value={form.city} onChangeText={set("city")} error={errors["property.address.city"]} required />
          <TextField className="flex-1" label="State" value={form.region} onChangeText={set("region")} autoCapitalize="characters" maxLength={2} error={errors["property.address.region"]} required />
        </View>
        <TextField label="ZIP" value={form.postalCode} onChangeText={set("postalCode")} keyboardType="number-pad" error={errors["property.address.postalCode"]} required />
        <Card className="flex-row items-center gap-3">
          <View className="flex-1">
            <Text variant="bodyStrong">Site location</Text>
            <Text variant="caption">{form.location ? `${form.location.latitude.toFixed(5)}, ${form.location.longitude.toFixed(5)}` : (errors.location ?? "Used for maps and weather. Capture while on site.")}</Text>
          </View>
          <Button label={form.location ? "Update" : "Use GPS"} icon="locate" size="md" variant="secondary" loading={locating} onPress={useGps} />
        </Card>

        {errors._ ? <Text className="text-sm text-destructive">{errors._}</Text> : null}
        <Button label="Create project" icon="checkmark" loading={create.isPending} onPress={() => create.mutate()} />
      </View>
    </Screen>
  );
}
